# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_shell.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_shell.proto',
  package='remote_shell',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12remote_shell.proto\x12\x0cremote_shell\"T\n\nClientInfo\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0f\n\x07os_info\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"?\n\x07\x43ommand\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0f\n\x07timeout\x18\x03 \x01(\x05\"h\n\rCommandResult\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x11\n\tclient_id\x18\x05 \x01(\t\"\x1e\n\nCommandAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\xa1\x01\n\x0bRemoteShell\x12\x44\n\rConnectClient\x12\x18.remote_shell.ClientInfo\x1a\x15.remote_shell.Command\"\x00\x30\x01\x12L\n\x11SendCommandResult\x12\x1b.remote_shell.CommandResult\x1a\x18.remote_shell.CommandAck\"\x00\x62\x06proto3')
)




_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='remote_shell.ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='remote_shell.ClientInfo.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='os_info', full_name='remote_shell.ClientInfo.os_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='remote_shell.ClientInfo.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='remote_shell.ClientInfo.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=120,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='remote_shell.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_id', full_name='remote_shell.Command.command_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='remote_shell.Command.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='remote_shell.Command.timeout', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=185,
)


_COMMANDRESULT = _descriptor.Descriptor(
  name='CommandResult',
  full_name='remote_shell.CommandResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_id', full_name='remote_shell.CommandResult.command_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='remote_shell.CommandResult.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='remote_shell.CommandResult.exit_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='remote_shell.CommandResult.error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='remote_shell.CommandResult.client_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=291,
)


_COMMANDACK = _descriptor.Descriptor(
  name='CommandAck',
  full_name='remote_shell.CommandAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='received', full_name='remote_shell.CommandAck.received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['CommandResult'] = _COMMANDRESULT
DESCRIPTOR.message_types_by_name['CommandAck'] = _COMMANDACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'remote_shell_pb2'
  # @@protoc_insertion_point(class_scope:remote_shell.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'remote_shell_pb2'
  # @@protoc_insertion_point(class_scope:remote_shell.Command)
  })
_sym_db.RegisterMessage(Command)

CommandResult = _reflection.GeneratedProtocolMessageType('CommandResult', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESULT,
  '__module__' : 'remote_shell_pb2'
  # @@protoc_insertion_point(class_scope:remote_shell.CommandResult)
  })
_sym_db.RegisterMessage(CommandResult)

CommandAck = _reflection.GeneratedProtocolMessageType('CommandAck', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDACK,
  '__module__' : 'remote_shell_pb2'
  # @@protoc_insertion_point(class_scope:remote_shell.CommandAck)
  })
_sym_db.RegisterMessage(CommandAck)



_REMOTESHELL = _descriptor.ServiceDescriptor(
  name='RemoteShell',
  full_name='remote_shell.RemoteShell',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=326,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConnectClient',
    full_name='remote_shell.RemoteShell.ConnectClient',
    index=0,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_COMMAND,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendCommandResult',
    full_name='remote_shell.RemoteShell.SendCommandResult',
    index=1,
    containing_service=None,
    input_type=_COMMANDRESULT,
    output_type=_COMMANDACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTESHELL)

DESCRIPTOR.services_by_name['RemoteShell'] = _REMOTESHELL

# @@protoc_insertion_point(module_scope)
